### ISSUE TITLE
daggone MPV4v2

### ISSUE THREAD

**Issue by RDYork** [JMoVS/installing_video_transcoding_on_windows#16]
The instruction at 2ii fails with this message:

> Package mp4v2-utils is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 
> E: Package 'mp4v2-utils' has no installation candidate

Note: I am running the Debian distro. If that is not a good thing, then maybe insert another instruction after 1v and recommend which distro to install. Actually, there really needs to be a step there anyway to instruct to install a distro I think

Thanks for the efforts
Randall

**Comment by samhutchins** [comment]
Yeah, the process for installing a distro has changed since I wrote these instructions. I'll get them updated, thanks!

I'd recommend using the Ubuntu 18.04 distro. 

I think that versions newer than 18.04 have also removed this package from the repositories, so until Don updates video_transcoding to remove the dependency on mp4v2 I'd say you should either stick to Ubuntu 18.04 or install the tool natively on Windows rather than using WSL.

**Comment by samhutchins** [comment]
I've updated the instructions in this commit: 9ca133041b727a74ca47aae8e426caa02a6c6f08
